export const LOAD_DATA = 'LOAD_DATA'
export const LOAD_DATA_ERROR = 'LOAD_DATA_ERROR'

export const SIGN_IN = 'SIGN_IN'
export const SIGN_UP = "SIGN_UP"
export const USER_UPDATED = 'USER_UPDATED'
export const RECORD_UPDATED = 'RECORD_UPDATED'
export const GARBAGE_UPDATED = 'GARBAGE_UPDATED'
export const EXCHANGE_UPDATED = 'EXCHANGE_UPDATED'
export const INVITE_UPDATED ='INVITE_UPDATED'
export const GUID_UPDATED = 'GUID_UPDATED'
export const HELP_UPDATED = 'HELP_UPDATED'
export const ARTICLE_UPDATED = 'ARTICLE_UPDATED'